
name: Repo Activity Test
on:
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EleonoraBorzis/repo-activity-report-action@main
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-name:  EleonoraBorzis/group-composition-action
          issue-number: 12
       
