
name: Repo Activity Test
on:
  pull_request_target:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EleonoraBorzis/repo-activity-action@Lizard
       
