
name: Repo Activity Test
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EleonoraBorzis/repo-activity-report-action@Lizard
       
