
name: Repo Activity Test
on:
  schedule:
    - cron: '0 8 30 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: EleonoraBorzis/repo-activity-report-action@main
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-name:  EleonoraBorzis/repo-activity-report-action
          issue-number: 12
       
